modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://www.github.com/xfacthd/framedblocks"
license="LGPL v3"

[[mods]]
modId="framedblocks"
version="${mod_version}"
displayName="FramedBlocks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/framedblocks"
logoFile="logo.png"
logoBlur=false
authors="XFactHD"
description='''
'''

[[mixins]]
    config="framedblocks.mixin.json"

[[dependencies.framedblocks]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="buildinggadgets"
    mandatory=false
    versionRange="[3.14.0,)"
    ordering="AFTER"
    side="BOTH"

#[[dependencies.framedblocks]]
#    modId="ctm"
#    mandatory=false
#    versionRange="[1.18-1.1.3+1,)"
#    ordering="AFTER"
#    side="CLIENT"

[[dependencies.framedblocks]]
    modId="diagonalfences"
    mandatory=false
    versionRange="[8.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="diagonalwindows"
    mandatory=false
    versionRange="[8.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="nocubes"
    mandatory=false
    versionRange="[1.19.1-0.5.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="jei"
    mandatory=false
    versionRange="[15.0.0.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="rei"
    mandatory=false
    versionRange="[12.0.634,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="emi"
    mandatory=false
    versionRange="[1.0.17,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="atlasviewer"
    mandatory=false
    versionRange="[5.1.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.framedblocks]]
    modId="modernfix"
    mandatory=false
    versionRange="[5.7.5,)"
    ordering="NONE"
    side="CLIENT"

[mods."modernfix:integration"]
    client_entrypoint="xfacthd.framedblocks.common.compat.modernfix.FramedModernFixClientIntegration"
