modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://www.github.com/xfacthd/framedblocks"
license="LGPL v3"

[[mods]]
modId="framedblocks"
version="${file.jarVersion}"
displayName="FramedBlocks"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="XFactHD"
description='''
'''
[[dependencies.framedblocks]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.59,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.framedblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
